# Etapa de ejecución (Liviana)
FROM eclipse-temurin:21-jre-alpine
WORKDIR /usr/local/lib

# Espera que el JAR ya esté en la carpeta target/ (construido localmente)
COPY target/gestorMateriasWeb-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
