# H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret.key=JHHZMdEk6zabyc5mfvxmz3L5BKp7z8ZEzdkN2Zw4cjI=
jwt.time.expiration=86400000

# Inicialización de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
